import { serve, type Server } from "bun";
import type {
  BoundServer,
  BunServer,
  DSRequest,
  DSResponse,
  GetHandler,
  HandlerTables,
  PostHandler,
  ServerOptions,
  ServerRef,
} from "../server";

export function sayHi() {
  console.log("hello from utils!");
}

export function forwardReq(R: Request, server: BunServer, handlerTables: HandlerTables): Response {
  //!! method routing here
  //!! get handlers are passed object extending Response with send method
  console.log("req: ", R);
  const DSRequest: DSRequest = R;
  const DSResponse: DSResponse = {
    send: null,
    closed: false,
    response: null,
  };

  DSResponse.send = createSend(DSResponse);

  let handler;
  if (R.method == "GET" || R.method == "POST") {
    handler = handlerTables[R.method][R.url]; //!! slice after tld
  }

  if (!handler || !handler.length) throw new Error("No request handler provided!");

  for (let i = 0; i < handler.length; i++) {
    handler[i] && handler[i]!(DSRequest, DSResponse); // cleanup assertion
  }

  // Response should be generated by DSRes.send() not from handler
  if (!DSResponse.closed || !DSResponse.response)
    throw new Error("Request connection not closed in handlers.");
  return DSResponse.response;
}

export function createServerRef(options?: ServerOptions): ServerRef {
  const handlerTables: HandlerTables = {
    GET: {},
    POST: {},
  };

  let serverRef: null | Server = null;

  const server: BoundServer = {
    get: (route: string, ...handlers: GetHandler[]) => {
      if (typeof route !== "string" || !handlers.length)
        throw new Error("GET handler misconfigured.");
      handlerTables.GET[route] = handlers;
    },
    post: (route: string, ...handlers: PostHandler[]) => {
      if (typeof route !== "string" || !handlers.length)
        throw new Error("GET handler misconfigured.");
      handlerTables.POST[route] = handlers;
    },
    listen: () => {
      if (typeof options === "object") {
        serverRef = serve({
          fetch: (R: Request, server: BunServer) => forwardReq(R, server, handlerTables),
          ...options,
        });
      }
    },
    kill: () => {
      if (!serverRef) throw new Error("No server to kill.");
      else serverRef.stop();
    },
  };

  return function () {
    return server;
  };
}

function createSend(resRef: DSResponse) {
  return function (args: [BodyInit?, ResponseInit?]) {
    if (!args.length) {
      throw new Error("'send' needs Response args.");
    }
    resRef.closed = true;
    return new Response(...args);
  };
}
